### ISSUE TITLE
Style item boxes when it has no description

### ISSUE THREAD

**Issue by Paalar** [appKom/nibble4#19]
As the image shows, there is a bit of white space left when there is no description of an item. Not sure how we should fix it, or if it is even necessary.

![image](https://user-images.githubusercontent.com/22390745/98662578-48be9880-2348-11eb-85d9-4fdf25ac282a.png)

**Comment by MartinSkatvedt** [comment]
The description is not necesarry in my opinion. The decription is often not very decriptive, and by removing it we wouldnt have to deal with this styling problem. The other nibble versions does not use it either.

**Comment by Paalar** [comment]
We can maybe remove it for now, and ask Trikom to create better descriptions instead. I think the problem is more that they're poorly used.
