### ISSUE TITLE
Proper scaling

### ISSUE THREAD

**Issue by MartinSkatvedt** [appKom/nibble4#35]
The app currently works fine on small screens (around 13''). But it should scale into bigger screens as well

**Comment by Paalar** [comment]
The UI issue is that the screen was cut at a certain height when the screen was not optimal. This could be solved by hard coding a specific value which would look good on a certain screen, but bad on another. It would work with the nibble machine, but if/when it gets replaced, it would no longer work unless the screens are the same.
