### ISSUE TITLE
Implement "newly-purchased"

### ISSUE THREAD

**Issue by MartinSkatvedt** [appKom/nibble4#44]
Implement a category that has the newly purchased items, or/and statistics for all your purchases,

**Comment by Jorrre** [comment]
I might have misunderstood when I created #65 as it doesn't list recently purchased items but rather all previously purchased items. However, #65 can provide as a starting point for this feature

**Comment by MartinSkatvedt** [comment]
When I created the feature request, I think I actually had in mind a "frequently purchased page", not a newly purchased one. This page could just take the n number of most purchased items and put them in the same page.
