### ISSUE TITLE
[BUG] Favourite tab, loading time 

### ISSUE THREAD

**Issue by MartinSkatvedt** [appKom/nibble4#73]
**Describe the bug**
The new favourite products tab makes the loading time for some users too long.

**To Reproduce**
1. Log in with lots of purchases

**Additional context**
This could be a problem with the endpoint, or the sorting algorithm that is being used.

**Comment by Jorrre** [comment]
I have created a [PR](https://github.com/dotkom/onlineweb4/pull/2696) on OW4 which limits the fetching of previous purchases to the 50 newest purchases. Should fix things for now, might create a more thorough fix at a later time.
